config/routes.rb
Rails.application.routes.draw do
  root "stack_word_trees#new"
  resources :stack_word_trees, except: [:update, :edit]
end

app/models/dictionary.rb
class Dictionary
  def initialize(data_file)
    @data_file = data_file
    read_file
  end

  def find_longest_word_stacked_tree
    @hash_with_length_as_key.keys.each do |key|
      log_process(key)
      words = @hash_with_length_as_key[key]
      words.each do |word|
        possible_trees = find_possible_permuted_trees(word: word)
        stack_tree     = find_full_stack_tree_in_trees(possible_trees)
        return stack_tree.reverse if stack_tree && stack_tree.count > 1
      end
    end
    []
  end

  private

  attr_reader :data_file

  def find_full_stack_tree_in_trees(trees)
    trees.values.reverse.find { |tree| has_full_stack_tree?(tree) }
  end

  def find_possible_permuted_trees(word: , possible_stacks: {}, previous_stack_key: nil)
    if possible_stacks.empty?
      previous_stack_key      = [word]
      possible_stacks[[word]] = [word]
    end

    possible_shorter_words = next_possible_shorter_words(word)
    new_stack              = create_new_stack_path(possible_stacks, previous_stack_key, word)
    return possible_stacks if has_full_stack_tree?(new_stack)
    find_next_possible_words(new_stack, possible_shorter_words, possible_stacks)

    possible_stacks
  end

  def create_new_stack_path(possible_stacks, previous_stack_key, word)
    new_stack                  = possible_stacks[previous_stack_key].dup.append(word).uniq
    possible_stacks[new_stack] = new_stack
    new_stack
  end

  def find_next_possible_words(new_stack, shorter_words, possible_stacks)
    return unless shorter_words.present?
    shorter_words.each do |possible_shorter_word|
      find_possible_permuted_trees(word:               possible_shorter_word,
                                   possible_stacks:    possible_stacks,
                                   previous_stack_key: new_stack)
    end
  end

  def next_possible_shorter_words(word)
    possible_shorter_words = []
    shorter_permutations   = shorter_permutations_of_word(word)
    shorter_permutations.each do |permutation|
      if @sorted_words[permutation.chars.sort.join]
        possible_shorter_words << @sorted_words[permutation.chars.sort.join]
      end
    end
    possible_shorter_words
  end

  def read_file
    @hash_with_length_as_key = {}
    @sorted_words            = {}

    File.readlines(data_file).each do |word|
      word.chomp!
      word.strip!
      next if word.empty?
      next if word.length < 3
      fill_hashes_with_word(word)
    end

    sort_hash_by_word_length
  end

  def fill_hashes_with_word(line)
    @hash_with_length_as_key[line.length] ||= []
    @hash_with_length_as_key[line.length] << line unless @hash_with_length_as_key[line.length].include?(line)
    @sorted_words[line.chars.sort.join] = line
  end

  def shorter_permutations_of_word(string)
    arr = []
    (0..string.length - 1).each do |i|
      str = string.dup
      str.slice!(i)
      arr << str.chars.sort.join.strip
    end
    arr.uniq
  end

  def sort_hash_by_word_length
    @hash_with_length_as_key = @hash_with_length_as_key.sort.reverse.to_h
  end

  def has_full_stack_tree?(new_stack)
    new_stack.last.length == 3
  end

  def log_process(key)
    Rails.logger.info("processing words with length: #{key}")
  end
end

app/models/stack_word_tree.rb
class StackWordTree < ActiveRecord::Base
  class NoDataFiledError < StandardError; end

  serialize :result, Array
  mount_uploader :data_file, ::DataFileUploader

  validates :data_file, presence: true

  after_create :generate_random_name

  def find_longest_stack_tree
    ensure_data_file_exists!
    self.result = Dictionary.new(data_file.file.file).find_longest_word_stacked_tree
    save
  end

  private

  def generate_random_name
    self.name = "#{Faker::App.name} Tree"
    save
  end

  def ensure_data_file_exists!
    fail NoDataFiledError, "No data file provided" if data_file.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stack_word_trees_controller.rb
class StackWordTreesController < ApplicationController
  before_action :set_stack_word_tree, only: [:show, :destroy]

  def index
    @stack_word_trees = StackWordTree.all
  end

  def show
  end

  def new
    @stack_word_tree = StackWordTree.new
  end

  def create
    @stack_word_tree = StackWordTree.new(stack_word_tree_params)

    respond_to do |format|
      if @stack_word_tree.save
        @stack_word_tree.find_longest_stack_tree
        format.html { redirect_to @stack_word_tree, notice: "Stack word tree was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @stack_word_tree.destroy
    respond_to do |format|
      format.html { redirect_to stack_word_trees_url, notice: "Stack word tree was successfully removed." }
    end
  end

  private

  def set_stack_word_tree
    @stack_word_tree = StackWordTree.find(params[:id])
  end

  def stack_word_tree_params
    #file field wont get set if user doesn't select it use fetch instead of require
    params.fetch(:stack_word_tree, {}).permit(:data_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"
      when "error"
        "alert-danger"
      when "alert"
        "alert-warning"
      when "notice"
        "alert-info"
      else
        "alert-info"
    end
  end

  def create_json_tree(stack_word_tree)
    tree = { name: "flare", children: [] }
    stack_word_tree.result.each do |result|
      tree[:children] << { name: result, size: result.length }
    end
    tree
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackedWordTree</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <script src="http://d3js.org/d3.v3.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "shared/nav" %>
    <%= render 'shared/flash_message' %>
    <%= render 'shared/header' %>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
      <%= render "shared/footer" %>

    </div>
  </body>
</html>

app/views/shared/_flash_message.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<hr>

<footer>
  <p>&copy; <%= DateTime.current.year %> StackedWordTree, Inc.</p>
</footer>

app/views/shared/_header.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Awesome Stacked WordTree!</h1>
    <p>Go ahead, upload a file and let our super AI figure out what the
      longest word containing a stacked tree is in your file.</p>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">StackedWordTree</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to("Home", root_path) %> </li>
        <li><%= link_to("Trees", stack_word_trees_path) %> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/stack_word_trees/_form.html.erb
<%= simple_form_for(@stack_word_tree) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :data_file %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Find My Stacked Word Tree", class: "btn btn-success" %>
    </div>
<% end %>

app/views/stack_word_trees/index.html.erb
<% if @stack_word_trees.any? %>
    <h1>Stack Word Trees</h1>
<% else %>
    <h1>No Stack Word Trees Available</h1>
<% end %>

<% @stack_word_trees.each do |stack_word_tree| %>
    <div class="well">
      <h3>My <%= stack_word_tree.name %></h3>
      <div class="tree-<%= stack_word_tree.id %>"></div>
      <%= link_to 'View Tree Details', stack_word_tree_path(stack_word_tree), class: "btn btn-default" %>
      <%= link_to 'Remove Tree', stack_word_tree, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    </div>

    <script>
      var treeData = <%= create_json_tree(stack_word_tree).to_json.html_safe %>;
      adgear.ui.stackWordTree.drawStackWordTree(".tree-<%= stack_word_tree.id.to_s %>", treeData);
    </script>
<% end %>

app/views/stack_word_trees/new.html.erb
<%= render 'form' %>

app/views/stack_word_trees/show.html.erb
<div class="row">
  <div class="col-md-12">
    <% if @stack_word_tree.result.blank? %>
        <h3>Sorry, it looks like this file doesn't have any stacked word trees!</h3>
    <% else %>
        <h3>Your stack tree is called <%= @stack_word_tree.name %>, take good care of it!</h3>
        <h4>Here is the stacked word tree of the longest word:</h4>
    <% end %>
    <hr>
  </div>
</div>

<div class="row">
  <div class="col-md-9">
    <div class="tree-<%= @stack_word_tree.id %>"></div>
  </div>

  <div class="col-md-3">
    <% unless @stack_word_tree.blank? %>
        <% @stack_word_tree.result.each do |result| %>
            <p><%= result %></p>
        <% end %>
    <% end %>
  </div>
</div>

<script>
  var treeData = <%= create_json_tree(@stack_word_tree).to_json.html_safe %>;
  adgear.ui.stackWordTree.drawStackWordTree(".tree-<%= @stack_word_tree.id.to_s %>", treeData);
</script>
<%= link_to("View All Trees", stack_word_trees_path, class: "btn btn-default") %>